WebSiteBanHang/Controllers/QuanLyKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;

namespace WebSiteBanHang.Controllers
{    
    public class QuanLyKhachHangController : Controller
    {
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: QuanLyKhachHang
        public ActionResult Index()
        {
            return View(db.ThanhViens.Where(n => n.MaLoaiTV == 3 || n.MaLoaiTV == 4));
        }

        [HttpGet]
        public ActionResult ThemThanhVien()
        {            
            return View();
        }

        public ActionResult ThemThanhVien(ThanhVien tv)
        {
            db.ThanhViens.Add(tv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            //Lấy tv cần chỉnh sửa
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
            if (tv == null)
            {
                return HttpNotFound();
            }            
            return View(tv);
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(ThanhVien model)
        {            
            //Nếu dữ liệu chắc chắn ok
            db.Entry(model).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult TiemNang()
        {         
            return View();
        }
    }
}

WebSiteBanHang/Views/QuanLyKhachHang/ChinhSua.cshtml
@model WebSiteBanHang.Models.ThanhVien

@{
    ViewBag.Title = "Chỉnh sửa thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Chỉnh sửa thành viên</h2>

@using (Html.BeginForm("ChinhSua", "QuanLyKhachHang", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("MaThanhVien", Model.MaThanhVien)
    <div class="form-group">
        @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
        </div>
    </div>
          
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

WebSiteBanHang/Views/QuanLyKhachHang/Index.cshtml
@using WebSiteBanHang.Models
@model IEnumerable<ThanhVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    //Khởi tạo control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}
@Html.ActionLink("Thêm mới thành viên", "ThemThanhVien", null, new { @class = "btn btn -success" })
<h3 style="text-align: center; color: red">Danh sách thành viên</h3>
<br />
<br />

@*Thể hiện dữ liệu thông qua control webGrid*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridRowStyle",
    columns: grid.Columns(
        grid.Column("MaThanhVien", "Mã thành viên"),
        grid.Column("TaiKhoan", "TaiKhoan"),
        grid.Column("DiaChi", "Địa chỉ"),
        grid.Column("Email", "Email"),
        grid.Column("SoDienThoai", "Số điện thoại"),
        grid.Column(format: p => Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = p.MaThanhVien }))
    ))

<style>
    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead > th > a {
        background-color: green;
    }

    .gridFooter {
        font-weight: bold;
    }
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

WebSiteBanHang/Views/QuanLyKhachHang/ThemThanhVien.cshtml
@model WebSiteBanHang.Models.ThanhVien
@{
    ViewBag.Title = "ThemThanhVien";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<br />
<br />
<br />
<h2 style="color: red; text-align: center">Thêm mới thành viên</h2>
<br /><br />

@using (Html.BeginForm("ThemThanhVien", "QuanLyKhachHang", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

      <div class="form-horizontal">
          @Html.ValidationSummary(true, "", new { @class = "text-danger" })

          <div class="form-group">
              @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
                  @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                  @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
              </div>
          </div>

          <div class="form-group">
              @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
                  @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                  @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
              </div>
          </div>

          <div class="form-group">
              @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
                  @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                  @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
              </div>
          </div>

          <div class="form-group">
              @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
                  @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                  @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
              </div>
          </div>

          <div class="form-group">
              @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
                  @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                  @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
              </div>
          </div>

          <div class="form-group">
              @Html.LabelFor(model => model.MaLoaiTV, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
                  @Html.EditorFor(model => model.MaLoaiTV, new { htmlAttributes = new { @class = "form-control" } })
                  @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
              </div>
          </div>
          <br />
          <br />
          <div class="form-group">
              <div class="col-md-offset-2 col-md-10">
                  <input type="submit" value="Tạo mới" class="btn btn-default" />
              </div>
          </div>
      </div>
        }

        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Trở về", "Index")
        </div>

WebSiteBanHang/Views/QuanLyKhachHang/TiemNang.cshtml
 @using WebSiteBanHang.Models
@model IEnumerable<DonDatHang>

@{
    ViewBag.Title = "TiemNang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    //Khởi tạo control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}
<h3 style="text-align: center; color: red">Danh sách khách hàng tiềm năng</h3>
<br />
<br />

@*Thể hiện dữ liệu thông qua control webGrid*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridRowStyle",
    columns: grid.Columns(
        grid.Column("MaDDH", "Mã đơn đặt hàng"),
        grid.Column("MaKH", "Mã khách hàng")       
    ))

<style>
    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead > th > a {
        background-color: green;
    }

    .gridFooter {
        font-weight: bold;
    }
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>