WebSiteBanHang/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;

namespace WebSiteBanHang.Controllers
{

    public class QuanLyDonHangController : Controller
    {
        // GET: QuanLyDonHang
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChuaThanhToan()
        {
            //Lấy danh sách các đơn hàng chưa duyệt
            var lst = db.DonDatHangs.Where(n => n.DaThanhToan == false).OrderBy(n => n.NgayDat);
            return View(lst);
        }

        public ActionResult ChuaGiao()
        {
            //Lấy danh sách các đơn hàng chưa giao
            var lstCG = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == false && n.DaThanhToan == false).OrderBy(n => n.NgayDat);
            return View(lstCG);
        }

        public ActionResult DaGiaoDaThanhToan()
        {
            //Lấy danh sách các đơn hàng đã giao đã thanh toán
            var lstDG = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == true && n.DaThanhToan == true).OrderBy(n => n.NgayDat);
            return View(lstDG);
        }

        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang model = db.DonDatHangs.SingleOrDefault(n => n.MaDDH == id);
            //Kiểm tra đơn đặt hàng có tồn tại
            if (model == null)
            {
                return HttpNotFound();
            }
            //Lấy danh sấch chi tiết đơn đặt hàng hiển thị cho người dùng thấy
            var lstChiTietHD = db.ChiTietDonDatHangs.Where(n => n.MaDDH == id);
            ViewBag.ListChiTietHD = lstChiTietHD;
            return View(model);
        }

        [HttpPost]
        public ActionResult DuyetDonHang(DonDatHang ddh, string Email)
        {
            //Truy vấn dữ liệu của đơn đặt hàng đó
            DonDatHang ddhUpdate = db.DonDatHangs.Single(n => n.MaDDH == ddh.MaDDH);
            ddhUpdate.DaThanhToan = ddh.DaThanhToan;
            ddhUpdate.TinhTrangGiaoHang = ddh.TinhTrangGiaoHang;
            db.SaveChanges();
            //Lấy danh sách chi tiết của đơn hàng để cho người dùng thấy
            var lstChiTietHD = db.ChiTietDonDatHangs.Where(n => n.MaDDH == ddh.MaDDH);
            ViewBag.ListChiTietHD = lstChiTietHD;
            string contentMail = "Đơn hàng của bạn đã được đặt thành công";
            if (ddhUpdate.DaThanhToan == false && ddhUpdate.TinhTrangGiaoHang == false)
            {
                contentMail = "Đơn hàng của bạn đã được tiếp nhận";
            }
            if (ddhUpdate.DaThanhToan == false && ddhUpdate.TinhTrangGiaoHang == true)
            {
                contentMail = "Đơn hàng của bạn đang được vận chuyển";
            }
            //Gửi email khách hàng xác nhận việc thanh toán
            GuiEmail("Xác nhận đơn hàng  của hệ thống ", Email, "quanghuy3748@gmail.com"
            , "1loinoidoingotngao", contentMail);
            return View(ddhUpdate);
        }

        public void GuiEmail(string Title, string ToEmail, string FromEmail, string PassWord, string Content)
        {
            //Gọi email
            MailMessage mail = new MailMessage();
            mail.To.Add(ToEmail); //Địa chỉ nhận
            mail.From = new MailAddress(ToEmail); //Địa chỉ gửi
            mail.Subject = Title; //Tiêu đề gửi
            mail.Body = Content; //Nội dung
            mail.IsBodyHtml = true;
            SmtpClient smpt = new SmtpClient();
            smpt.Host = "smtp.gmail.com";
            smpt.Port = 587;
            smpt.UseDefaultCredentials = false;
            smpt.Credentials = new System.Net.NetworkCredential(FromEmail, PassWord);
            smpt.EnableSsl = true; // kích hoạt giao tiếp an toàn ssl
            smpt.Send(mail); //gửi email đi
        }
    }
}

WebSiteBanHang/Views/QuanLyDonHang/ChuaGiao.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa giao)</h2>
<br />
@*Tab quản lý trạng thái đơn hàng*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("ChuaThanhToan", "QuanLyDonHang")">Tiếp nhận</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Đang giao hàng</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Hoàn thành</a></li>
</ul>

@*Dùng control WebGrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridRowStyle",
    columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn hàng"),
        grid.Column("MaKH", header: "Họ tên khách hàng", format: p=>p.MaKH !=null ? p.KhachHang.TenKH : ""),
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),
        //grid.Column("DaHuy", header: "Đã huỷ"),
        grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang",
        new { id = p.MaDDH}, new { @target = "_blank" }))

    ))

<style>
    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead > th > a {
        background-color: green;
    }

    .gridFooter {
        font-weight: bold;
    }
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

WebSiteBanHang/Views/QuanLyDonHang/ChuaThanhToan.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa thanh  toán)</h2>
<br />
@*Tab quản lý trạng thái đơn hàng*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("ChuaThanhToan", "QuanLyDonHang")">Tiếp nhận</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Đang giao hàng</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Hoàn thành</a></li>
</ul>

@*Dùng control WebGrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridRowStyle",
    columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn hàng"),
        grid.Column("MaKH", header: "Họ tên khách hàng", format: p=>p.MaKH !=null ? p.KhachHang.TenKH : ""),
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),
        //grid.Column("DaHuy", header: "Đã huỷ"),
        grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang",
        new { id = p.MaDDH}, new { @target = "_blank" }))

    ))

<style>
    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead > th > a {
        background-color: green;
    }

    .gridFooter {
        font-weight: bold;
    }
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

WebSiteBanHang/Views/QuanLyDonHang/DaGiaoDaThanhToan.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng đã thành công)</h2>
<br />
@*Tab quản lý trạng thái đơn hàng*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("ChuaThanhToan", "QuanLyDonHang")">Tiếp nhận</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Đang giao hàng</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Hoàn thành</a></li>
</ul>

@*Dùng control WebGrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridRowStyle",
    columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn hàng"),
        grid.Column("MaKH", header: "Họ tên khách hàng", format: p=>p.MaKH !=null ? p.KhachHang.TenKH : ""),
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),        
        grid.Column("UuDai", header: "Ưu đãi"),
        //grid.Column("DaHuy", header: "Đã huỷ"),
        grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang",
        new { id = p.MaDDH}, new { @target = "_blank" }))

    ))

<style>
    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead > th > a {
        background-color: green;
    }

    .gridFooter {
        font-weight: bold;
    }
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

WebSiteBanHang/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using WebSiteBanHang.Models;
@model DonDatHang

@{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<h2>Thông tin đơn hàng <font color="blue">@Model.KhachHang.TenKH</font></h2>

<br />

@using (Html.BeginForm())
{
    <div class="ChiTietDonHang table">
        @{ IEnumerable<ChiTietDonDatHang> lstChiTietHD = (IEnumerable<ChiTietDonDatHang>)ViewBag.ListChiTietHD;}
        <table class="table" id="table">
            @*Phần thông tin đơn hàng*@
            <tr>
                <td colspan="4">
                    <table style="width: 100%">
                        <tr>
                            <td>Mã đơn hàng: <b style="color: red">@Model.MaDDH @Html.Hidden("MaDDH", @Model.MaDDH)</b></td>
                            <td>Mã khách hàng: <b style="color: red">@Model.KhachHang.MaKH </b></td>
                            <td>Tên khách hàng: <b style="color: red">@Model.KhachHang.TenKH</b></td>
                            <td>Email: <b style="color: red">@Model.KhachHang.Email @Html.Hidden("Email", @Model.KhachHang.Email)</b></td>
                            <td>Ngày đặt: @Model.NgayDat.Value.ToString("dd/MM/yyyy")</td>
                            <td>Đã thanh toán: @Html.EditorFor(model => model.DaThanhToan)</td>
                            <td>Đã giao: @Html.EditorFor(model => model.TinhTrangGiaoHang)</td>
                        </tr>
                    </table>

                </td>
            </tr>

            @*Thông tin chi tiết đơn hàng*@
            <tr>
                <td><b>Sản phẩm</b></td>
                <td><b>Hình ảnh</b></td>
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>

            @foreach (var item in lstChiTietHD)
            {
                <tr>
                    <td>@item.SanPham.TenSP</td>
                    <td><img width="150" height="50" src="@Url.Content("~/Content/HinhAnhSP/" + item.SanPham.HinhAnh)" /></td>
                    <td>@item.SoLuong</td>
                    <td>@item.DonGia</td>
                </tr>
            }
            <tr>
                <td align="right" colspan="4">Tổng số lượng: @Model.ChiTietDonDatHangs.Sum(n => n.SoLuong) sản phẩm</td>
            </tr>
            <tr>
                <td align="right" colspan="4">Tổng tièn: @Model.ChiTietDonDatHangs.Sum(n => n.SanPham.DonGia).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br />
        <br />
        <input type="button" id="btnInDonHang" value="In đơn hàng" />
        <input type="submit" id="btnInDonHang" value="Lưu đơn hàng" />
    </div>
}

<script>
    $("#btnInDonHang").click(function () {
        var content = "<table>" + $("#table").html() + "</table>";
        InDonHang(content);
    });

    //Phương thức in
    function InDonHang(content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>Đơn hàng</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>

WebSiteBanHang/Views/QuanLyDonHang/GuiKH.cshtml
@{
    ViewBag.Title = "GuiKH";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Gửi KH</h2>

WebSiteBanHang/Views/QuanLyDonHang/Index.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa thanh  toán)</h2>
<br />
@*Tab quản lý trạng thái đơn hàng*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("ChuaThanhToan", "QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & đã thanh toán</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>