WebSiteBanHang/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string CauHinh { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotBinhLuan { get; set; }
        public Nullable<int> SoLanMua { get; set; }
        public Nullable<int> Moi { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}

WebSiteBanHang/Controllers/BnhLuanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;

namespace WebSiteBanHang.Controllers
{
    public class BinhLuanController : Controller
    {
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: BinhLuan
        [HttpPost]
        public ActionResult Create(int? MaSP, string NoiDung, int? MaTV, DateTime? NgayBL)
        {
            if (MaSP == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == MaSP && n.DaXoa == false);

            if (sp == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSP = MaSP;
            BinhLuan bl = new BinhLuan();
            bl.MaSP = MaSP;
            bl.MaThanhVien = MaTV;
            bl.NoiDungBL = NoiDung;
            bl.NgayBL = NgayBL;
            db.BinhLuans.Add(bl);
            db.SaveChanges();
            return RedirectToAction("XemChiTietSP", "SanPham", new { id = MaSP });
        }

        public ActionResult Index(int? id, int? MaTV)
        {
            ViewBag.MaSP = id;
            ViewBag.MaThanhVien = MaTV;
            return View();
        }       
    }
}

WebSiteBanHang/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;
using PagedList;

namespace WebSiteBanHang.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        //Sử dụng partial view
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        //Tạo 2 partial view sản phẩm 1 và 2 để hiển thị sản phẩnm
        [ChildActionOnly]
        public ActionResult DTMoiNhatPartial()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult LTMoiNhatPartial()
        {
            return PartialView();
        }

        public ActionResult DanhMucPartial()
        {
            return PartialView();
        }

        public ActionResult SPChayNhatPartial()
        {
            var lstSP = db.SanPhams.Max(n => n.SoLanMua);
            return PartialView(lstSP);
        }

        public ActionResult ThuongHieuPartial()
        {
            return PartialView();
        }

        //Xây dựng action load sản phẩm theo mã loại sản phẩm và mã nhà sản xuất
        public ActionResult SanPham(int? MaloaiSP, int? MaNSX, int? page)
        {
            //if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            //{
            //    return RedirectToAction("Index", "Home");
            //}
            if (MaloaiSP == null || MaNSX == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Load sản phẩm dựa theo 2 tiêu chí là Mã loại sản phẩm và Mã nhà sản xuất
            var lstSP = db.SanPhams.Where(n => n.MaLoaiSP == MaloaiSP && n.MaNSX == MaNSX);
            if (lstSP.Count() == 0)
            {
                return HttpNotFound();
            }
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            //Thực hiện chức năng phân trang
            //Tạo biến số sản phẩm trên trang
            int PageSize = 6;
            //Tạo biến thứ 2: Số trang hiện tại
            int PageNumber = (page ?? 1);
            ViewBag.MaLoaiSP = MaloaiSP;
            ViewBag.MaNSX = MaNSX;
            return View(lstSP.OrderBy(n => n.MaSP).ToPagedList(PageNumber, PageSize));
        }

        public ActionResult XemChiTietSP(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id && n.DaXoa == false);

            if (sp == null)
            {
                return HttpNotFound();
            }          
            return View(sp);
        }
    }
}

WebSiteBanHang/Views/SanPham/DTMoiNhatPartial.cshtml
@using WebSiteBanHang.Models;
@model IEnumerable<SanPham>


        @foreach (var item in Model.Take(3))
        {
        <div class="col-md-4 grid-top">
            <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
                <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + item.HinhAnh)" alt="">
                <div class="b-wrapper">
                    <h3 class="b-animate b-from-left    b-delay03 " style="text-align:left; font-size:15pt;">
                        @*<span>@Html.Raw(item.CauHinh)</span>*@
                    </h3>
                </div>
            </a>


            <p><a href="single.html">@item.TenSP</a></p>
        </div>
        }
        <div class="clearfix"> </div>

WebSiteBanHang/Views/SanPham/DanhMucPartial.cshtml
@using WebSiteBanHang.Models
@model IEnumerable<SanPham>
<div class="sellers">
    <div class="of-left-in">
        <h3 class="tag">Thương hiệu</h3>
    </div>
    <div class="tags">
        @foreach (var groupItem in Model.GroupBy(n => n.LoaiSanPham))
        {
            if (groupItem.Key != null)
            {
                <ul>
                    @foreach (var item in groupItem.GroupBy(n => n.NhaSanXuat))
                    {
                        <li><a href="@Url.Action("SanPham","SanPham", new {@MaLoaiSP= groupItem.Key.MaLoaiSP, @MaNSX=item.Key.MaNSX })">@item.Key.TenNSX</a></li>                        
                    }
                </ul>
            }
        }
        <div class="clearfix"> </div>
    </div>

</div>

WebSiteBanHang/Views/SanPham/LTMoiNhatPartial.cshtml
@using WebSiteBanHang.Models;
@model IEnumerable<SanPham>

<div class="content-top-bottom">
    @foreach (var item in Model.Take(1))
    {
        <div class="col-md-6 men">
            <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
                <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + @Model.ElementAt(0).HinhAnh)" alt="">
                <div class="b-wrapper">
                    <h3 class="b-animate b-from-top top-in   b-delay03 ">
                        <span>@Html.Raw(Model.ElementAt(0).CauHinh)</span>
                    </h3>
                </div>
            </a>
            <h3>@Model.ElementAt(0).TenSP</h3>

        </div>
        <div class="col-md-6">
            <div class="col-md1 ">
                <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
                    <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + @Model.ElementAt(1).HinhAnh)" alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-top top-in1   b-delay03 ">
                            <span>@Html.Raw(Model.ElementAt(1).CauHinh)</span>
                        </h3>
                    </div>
                </a>
                <h3>@Model.ElementAt(1).TenSP</h3>
            </div>
            <div class="col-md2">
                <div class="col-md-6 men1">
                    <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
                        <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + @Model.ElementAt(2).HinhAnh)" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-top top-in2   b-delay03 ">
                                <span>@Html.Raw(Model.ElementAt(2).CauHinh)</span>
                            </h3>
                        </div>
                    </a>
                    <h3>@Model.ElementAt(2).TenSP</h3>
                </div>
                <div class="col-md-6 men2">
                    <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
                        <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + @Model.ElementAt(3).HinhAnh)" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-top top-in2   b-delay03 ">
                                <span>@Html.Raw(Model.ElementAt(3).CauHinh)</span>
                            </h3>
                        </div>
                    </a>
                    <h3>@Model.ElementAt(3).TenSP</h3>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    }

</div>

WebSiteBanHang/Views/SanPham/SPChayNhatPartial.cshtml
@using WebSiteBanHang.Models;
@model IEnumerable<SanPham>

<div class="product-bottom">
    <div class="of-left-in">
        <h3 class="best">Sản phẩm chạy nhất</h3>
    </div>
    @foreach (var item in Model.Take(3))
    {
        <div class="product-go">
            <div class=" fashion-grid">
                <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })"><img class="img-responsive " src="@Url.Content("~/Content/HinhAnhSP/" + item.HinhAnh)" alt=""></a>

            </div>
            <div class=" fashion-grid1">
                <h6 class="best2">
                    <a href="@Url.Action("XemChiTietSP","SanPham", new { id = item.MaSP })">
                        @item.TenSP
                    </a>
                </h6>

                <span class=" price-in1">@item.DonGia</span>
            </div>

            <div class="clearfix"> </div>
        </div>
    }


</div>

WebSiteBanHang/Views/SanPham/SanPham.cshtml
@using WebSiteBanHang.Models
@using PagedList.Mvc;

@model PagedList.IPagedList<SanPham>
@{
    ViewBag.Title = "SanPham";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}

<div class="col-md-9 product1">
    <div class=" bottom-product">
        @foreach (var item in Model.OrderBy(n => n.DonGia))
        {
            <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                <div class="product-at ">
                    <a href="single.html">
                        <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" +item.HinhAnh)" alt="">
                        <div class="pro-grid">
                            <a class="buy-in" href="/SanPham/XemChiTietSP?id=@item.MaSP">Xem chi tiết</a>
                        </div>
                    </a>
                </div>
                <p class="tun">@item.TenSP</p>
                @*Thẻ a nút thêm*@
                <a href="@Url.Action("ThemGioHang","GioHang", new { @MaSP = item.MaSP, @strURL = Request.Url.ToString()} )" class="item_add"><p class="number item_price"><i> </i>@item.DonGia.Value.ToString("#,##")</p></a>
            </div>
        }
        <div class="clearfix"> </div>
    </div>
    </div>

<div class="dlink">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("SanPham", new { page = page, @MaLoaiSP = ViewBag.MaLoaiSP, @MaNSX = ViewBag.MaNSX}))
</div>

WebSiteBanHang/Views/SanPham/ThuongHieuPartial.cshtml
@using WebSiteBanHang.Models
@model IEnumerable<SanPham>

<ul class="menu">
    @foreach (var groupItem in Model.GroupBy(n => n.LoaiSanPham))
    {
        if (groupItem.Key != null)
        {
            <li class="item1">
                <a href="#" class="">@groupItem.Key.TenLoai </a>
                <ul class="cute" style="display: none;">
                    @foreach (var item in groupItem.GroupBy(n => n.NhaSanXuat))
                    {
                        <li><a href="@Url.Action("SanPham","SanPham", new {@MaLoaiSP= groupItem.Key.MaLoaiSP, @MaNSX=item.Key.MaNSX })">@item.Key.TenNSX</a></li>
                    }
                </ul>
            </li>
        }

    }

</ul>

WebSiteBanHang/Views/SanPham/VietBinhLuan.cshtml
@model IEnumerable<WebSiteBanHang.Models.BinhLuan>
@{
    ViewBag.Title = "VietBinhLuan";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}
<h3>Bình luận</h3>
@if (Session["TaiKhoan"] == null)
{
    <a href="#">Bạn cần đăng nhập để bình luận</a>
}
else
{
    using (Html.BeginForm("VietBinhLuan", "SanPham", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("MaSP", (int?)ViewBag.MaSP)
        @Html.TextArea("NoiDung")
        <input type="submit" value="Đăng" />
    }
    <div id="comments">
        @foreach (var item in Model)
        {
        <div class="comment">
            <div class="comment-name">@item.NoiDungBL</div>
            <div class="comment-content">@item.MaSP</div>
        </div>
        }        
    </div>
    
}

WebSiteBanHang/Views/SanPham/XemChiTietSP.cshtml
@using WebSiteBanHang.Models;
@model SanPham
@{
    ViewBag.Title = "XemChiTietSP";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}

<div class="col-md-9 product-price1">
    <div class="col-md-5 single-top">
        <div class="flexslider">
            <ul class="slides" style="width: 1200%; transition-duration: 0s; transform: translate3d(-304px, 0px, 0px);">
                <li data-thumb="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh)">
                    <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh)" />
                </li>
            </ul>
        </div>
        <!-- FlexSlider -->
        <script defer="" src="~/Content/js/jquery.flexslider.js"></script>
        <link rel="stylesheet" href="~/Content/css/flexslider.css" type="text/css" media="screen">

        <script>
            // Can also be used with $(document).ready()
            $(window).load(function () {
                $('.flexslider').flexslider({
                    animation: "slide",
                    controlNav: "thumbnails"
                });
            });
        </script>
    </div>
    <div class="col-md-7 single-top-in simpleCart_shelfItem">
        <div class="single-para ">
            <h4>@Model.TenSP</h4>
            <div class="star-on">
                <ul class="star-footer">
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                </ul>
                <div class="review">
                    <a href="#"> Lượt xem: @Model.LuotXem </a>

                </div>
                <div class="clearfix"> </div>
            </div>

            <h5 class="item_price">@Model.DonGia.Value.ToString("#,##") VNĐ</h5>
            <h3 style="color:black">Thông số kỹ thuật</h3>
            <p>
                @Html.Raw(Model.CauHinh)
            </p>
            <a href="@Url.Action("ThemGioHang","GioHang", new { @MaSP = Model.MaSP, @strURL = Request.Url.ToString()} )" class="add-cart item_add">Giỏ hàng</a>
        </div>

    </div>
    <br />
    <div class="clearfix"> </div>
    <div class="row">
        <div class="col-md-12">
            @if (Session["TaiKhoan"] != null)
            {
                @Html.Action("Index","BinhLuan", new { MaSP = Model.MaSP})
            }
            else
            {
            <a href="#">Bạn phải đăng nhập để bình luận</a>
            }
        </div>
    </div>

    <hr />
    @Html.Raw(Model.MoTa)
    <!---->


</div>